name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Git Bisect
        env:
          BAD_COMMIT: "bad-hash-goes-here"  # Remplacez par le hash du commit mauvais
          GOOD_COMMIT: "good-hash-goes-here"  # Remplacez par le hash du commit bon
        run: |
          python myscript.py $BAD_COMMIT $GOOD_COMMIT
      - name: Run tests
        run: python manage.py test